### ISSUE TITLE
dxf doesn't generate properly

### ISSUE THREAD

**Issue by 4rz0** [paulius-zubavicius/pulleys-profile-generator#1]
I tried using the tool with the example settings, and a dxf is generated which contains data.
However, neither program I tried can work with the generated file.
I tried opening/importing it into inkscape, which does nothing. Same goes for importing it into OpenSCAD and OneShape. No errors are thrown in either of these programs.

Attached is the locally generated file:
[pulley_HTD_5mm_40.zip](https://github.com/paulius-zubavicius/pulleys-profile-generator/files/1874780/pulley_HTD_5mm_40.zip)

**Comment by paulius-zubavicius** [comment]
Hi, you right it doesn't work with Incspace now. I will fix that issue, thanks for your message.

**Comment by paulius-zubavicius** [comment]
Fixed. It seems there was a problem with older dxf format. Inkscape just ignoring the polygon data and opening as empty project. Checked with Inkscape 0.91 and FreeCAD 0.17
Cheers!
